---
title: "Cytotoxicity Concentration-Response Modeling"
author: Sierra Boyd
output:
  html_document:
    theme:
    toc: false
    code_folding: hide
editor_options: 
  chunk_output_type: console
---
```{r load packages}

library(tidyverse)
library(dplyr)
library(tidyr)
library(magrittr)
library(ggplot2)
library(ggpubr)
library(ggpattern)
library(tcpl)
library(tcplfit2)
library(stringr)
library(data.table)
library(openxlsx)
library(readxl)
library(conflicted)
library(pheatmap)

conflicts_prefer(purrr::transpose())
conflicts_prefer(dplyr::filter())

```

```{r}
#Set working directory
setwd("~")
```


#Import files and arrange data
```{r}
#Indicate input directory
project.input.dir <-"~"

#Make list of data files 
csv_files<- list.files(path=project.input.dir, pattern = "Blue\\.csv$", recursive = T, full.names = T) 

#Make vector for what the names of the basenames of the data files
data_frame_names<-gsub("Blue.csv","",basename(csv_files))

#Read in data file, melt to long format, and create an identifier
 for (i in csv_files){
   CellTiter<-fread(i) #read in all csv files
   CellTiter <- melt(CellTiter, id.vars = c("Dose"), #melt to a long data format
                           measure.vars=c("Loperamide_Plate1","Loperamide_Plate2","Loperamide_Plate3","Dieldrin_Plate1","Dieldrin_Plate2","Dieldrin_Plate3","Dieldrin_Plate4","Deltamethrin_Plate1","Deltamethrin_Plate2","Deltamethrin_Plate3","Deltamethrin_Plate4","Glyphosate_Plate1","Glyphosate_Plate2","Glyphosate_Plate3","Glyphosate_Plate4"),variable.name="Identifer", value.name="rval")
   CellTiter<-separate(CellTiter, Identifer, into=c("Chemical","Plate"), sep="_") #Separate column names into chemical ankd plate 
   CellTiter<-as.data.table(CellTiter) #make a dt
 }

```


```{r}
#Remove any na values for rval
CellTiter <- subset(CellTiter, !is.na(rval))

#acnm is the tcplfit2 name for Endpoint/Assay. Here we will set it to CellTiter
CellTiter$acnm<-"CellTiter"

#Create Binary column to indicate controls. Controls will be call n (non-treated), treated cells will be called t. wllt=well treatment
CellTiter <- CellTiter[, wllt := ifelse(Dose %in% 0e+00, 'n','t')]

#calculate baseline value or median of controls
CellTiter[,bval:=median(rval[wllt=='n']),by=Plate]

#Calculate Response by normalizing to bval (response-baseline response / baseline response *100)
CellTiter <- CellTiter[,resp := ((rval - bval) / bval)* 100]

#calculate mad of baseline values (MAD= Median absolute deviation)
##only 
CellTiter[, bmad := mad(resp[wllt %in% 'n'])]

#Set cut off (coff) value to 3*bmad (this is how the conc-response modeling determines a hit by assessing if a response value deviates from the median greater than the cut off value )
#CellTiter[, coff := 3*bmad]
CellTiter[, coff := 18.4]

#Set cut off as 30 if greater than 30 or less than 10
#A cut off of 10 is too conservative and a cut off of 30 is to lax (based on historical values from the Shafer Lab)
#CellTiter$coff[CellTiter$coff>=30]<-30
#CellTiter$coff[CellTiter$coff<=10]<-30

#Calculate standard deviation for all of the controls 
CellTiter[, onesd := sd(resp[wllt %in% 'n'])]

#Make sure response is numeric
CellTiter$resp<-as.numeric(CellTiter$resp)

#Need to mutate controls so we can do log10 of doses (Cannot calculate log10 of 0 value, so set 0 to a very low number such as 0.0001)
CellTiter <- CellTiter %>%
  mutate(
    Dose = ifelse(Dose == 0.0000,0.0001,Dose )
  )

CellTiter<-CellTiter%>%filter(!Dose==0.0001)

#Update nomenclature
setnames(CellTiter,"Dose","conc")
setnames(CellTiter,"Chemical","trt")


```

#Fit to curve using tcplfit2
##End results are in res table (ignore res_1)
```{r}
#set up for loop to call acnm and chemical 
res <- data.frame()
datalist <- list()


for(i in 1:length(unique(CellTiter$acnm))){
  this.aenm <- unique(CellTiter$acnm)[i]
  aenm.temp <- CellTiter[acnm == this.aenm, ]
  #aenm.temp[, aenm := this.aenm]
  for(j in 1:length(unique(aenm.temp$trt))){ # used ii so that i isn't being overwritten
    this.trt <- unique(aenm.temp$trt)[j]
    this.apid <- unique(aenm.temp[trt %in% this.trt, Plate]) # need to subset by apid
    temp <- aenm.temp[trt == this.trt | (Plate %in% this.apid & wllt %in% 'n'), ]
    temp[, trt := trt]
    row = list(conc=temp$conc, # use conc from the subset
               resp=temp$resp, # use resp from the subset, note from 03/04/2024: resp is not getting updated by chemical it's all the same for each row
               bmed= 0, # 0 since we are working with a normalized percent scale
               cutoff= unique(temp$coff), # find cutoff using 3bmad for EACH aenm (i)
               # cutoff= unique(temp$coff), # find cutoff using 3bmad for EACH aenm (i)
               onesd= unique(temp$onesd), # find sd for EACH aenm (i)
               name= this.trt, # update here as well
               assay= unique(temp$acnm)) # instead of assay we can use this to identify the endpoint for each curve fit 
    # run concentration-response modeling (1st plotting option)
    out = concRespCore(row,
                       fitmodels = c("cnst", "hill", "gnls", "poly1", "poly2", "pow", "exp2", "exp3", "exp4",
                                     "exp5"),conthits=TRUE,do.plot=FALSE)
    datalist[[j]] <- out
    res1 <- do.call(rbind, datalist)
  }  
  res <- rbind(res, res1)
}



setDT(res)
res[, hitc := ifelse(hitcall>=0.9,1,0)]
res[hitc==1, c('name','assay')] 

# save res file as an excel
write.xlsx(res, './Activity_Scan_tcplfit2_SpecificDOPs.xlsx')

#Check the pdf that is created to see how the data fits to a curve for conc-response modeling
file.dir <- paste("~", sep="")
file.name <- paste0("/CellTiter_res_", Sys.Date(), ".pdf", sep="")
file.path <- paste(file.dir, file.name, sep="")
dir.create(path=file.dir, showWarnings = FALSE, recursive = TRUE)
pdf(file.path, 
    width = 12, 
    height = 10)
# plot results using `concRespPlot`(2nd plotting option)
for(i in 1:nrow(res)){
  concRespPlot(res[i,],ymin=-100,ymax=250) #Adjust the y axis of the plots here
}

dev.off()

#Check the res file to see hits 
```

