---
title: "CV Analysis for General Activity, Neural Network, and Action Potential Propagation"
author: Sierra Boyd
output:
  html_document:
    theme: cerulean
    toc: false
    code_folding: hide
editor_options: 
  chunk_output_type: console
---
```{r load packages}

library(tidyverse)
library(dplyr)
library(tidyr)
library(readxl)
library(pracma)
library(conflicted)
library(data.table)

conflicts_prefer(dplyr::filter())

```

```{r}
#Set wd to an an "export" folder
setwd("~")
```

#Calculate CVs for General Activity
```{r}
#Indicate input directory
project.input.dir <-"~"

#Make list of data files 
csv_files<- list.files(path=project.input.dir, pattern = "_Melt\\.csv$", recursive = T, full.names = T) 

#Make vector for what the names of the basenames of the data files
data_frame_names<-gsub("_Melt.csv","",basename(csv_files))

#load csv files
for (i in csv_files){
  df<-fread(i)
  Activity_Scan<-df
}

#Remove DOP 2 and 28 (Pre-Treatment and Washout Days)
Activity_Scan<-subset(Activity_Scan %>% filter(!grepl(28,DOP)))
Activity_Scan<-subset(Activity_Scan %>% filter(!grepl("\\b2\\b",DOP)))

#Determine plate type here. Plate serial numbers starting in T are 24-well plate and serial numbers starting in M are 6-well plates
Activity_Scan<-Activity_Scan%>%
  mutate(Plate_Type=ifelse(grepl("T",Group_ID),"Twenty_four","Six"))

#Subset control values only 
Activity_Controls<-Activity_Scan %>% filter((Dosage== "Control"))

#Check for NAs and remove
Activity_Controls<-Activity_Controls%>% filter(!is.na(value))

#set variables as numeric
Activity_Controls$value<-as.numeric(Activity_Controls$value)

#calculate a baseline value by taking the median by endpoint, plate_type and DOP
Activity_Controls[,bval:=median(value),by=c("Endpoint","Plate_Type","DOP")]

#Check for NAs and remove
Activity_Controls <- Activity_Controls[!is.na(bval),]

#Calculate response values by normalizing to bval
Activity_Controls <- Activity_Controls[,resp := ((value) / bval)]

#Group by sample and endpoint
Activity_auc_df<-Activity_Controls %>%
  arrange(DOP)%>%
  group_by(Group_ID,Endpoint) %>%
  summarize (AUC=trapz(DOP,resp))%>%
  ungroup()

#Calculate Median by Endpoint
Activity_Medians<-Activity_auc_df %>%
  group_by(Endpoint) %>%
  summarize (Median=median(AUC))%>%
  ungroup()

#Calculate MAD by Endpoint
Activity_MADs<-Activity_auc_df %>%
  group_by(Endpoint) %>%
  summarize (MAD=mad(AUC))%>%
  ungroup()

#Full join back to one df
Activity_Median_MADs <- full_join(Activity_Medians,Activity_MADs, by = c("Endpoint"))

#Calculate CVs based on median and MAD
Activity_CV_Median_Mad<-Activity_Median_MADs%>%
  group_by(Endpoint) %>%
  summarize (CV_Median_MAD=MAD/Median)%>%
  ungroup()

#Export
write.csv(Activity_CV_Median_Mad,file = "~",row.names=F)

```

#Calculate CVs for Neural Network
```{r}
#Indicate input directory
project.input.dir <-"~"

#Make list of data files 
csv_files<- list.files(path=project.input.dir, pattern = "_Melt\\.csv$", recursive = T, full.names = T) 

#Make vector for what the names of the basenames of the data files
data_frame_names<-gsub("_Melt.csv","",basename(csv_files))

#load csv files
for (i in csv_files){
  df<-fread(i)
  df<-df[,-1]
  Network_Scan<-df
}

#Check for NAs and remove
Network_Scan<-Network_Scan%>% filter(!is.na(value))

#Remove DOP 2 and 28 (Pre-Treatment and Washout Days)
Network_Scan<-subset(Network_Scan %>% filter(!grepl(28,DOP)))
Network_Scan<-subset(Network_Scan %>% filter(!grepl("\\b2\\b",DOP)))

#Determine plate type here. Plate serial numbers starting in T are 24-well plate and serial numbers starting in M are 6-well plates
Network_Scan<-Network_Scan%>%
  mutate(Plate_Type=ifelse(grepl("T",Group_ID),"Twenty_four","Six"))

#Subset control values only 
Network_Controls<-Network_Scan %>% filter((Dosage== "Control"))

#Check for NAs and remove
Network_Controls<-Network_Controls%>% filter(!is.na(value))

#set variables as numeric
Network_Controls$value<-as.numeric(Network_Controls$value)

#calculate a baseline value by taking the median by endpoint, plate_type and DOP
Network_Controls[,bval:=median(value),by=c("Endpoint","Plate_Type","DOP")]

#Check for NAs and remove
Network_Controls <- Network_Controls[!is.na(bval),]

#Calculate response values by normalizing to bval
Network_Controls <- Network_Controls[,resp := ((value) / bval)]

#Group by sample and endpoint
Network_auc_df<-Network_Controls %>%
  arrange(DOP)%>%
  group_by(Group_ID,Endpoint) %>%
  summarize (AUC=trapz(DOP,resp))%>%
  ungroup()


#Calculate Median by Endpoint
Network_Medians<-Network_auc_df %>%
  group_by(Endpoint) %>%
  summarize (Median=median(AUC))%>%
  ungroup()

#Calculate MAD by Endpoint
Network_MADs<-Network_auc_df %>%
  group_by(Endpoint) %>%
  summarize (MAD=mad(AUC))%>%
  ungroup()

#Full join back to one df
Network_Median_MADs <- full_join(Network_Medians,Network_MADs, by = c("Endpoint"))

#Calculate CVs based on median and MAD
Network_Median_MADs<-Network_Median_MADs%>%
  group_by(Endpoint) %>%
  summarize (CV_Median_MAD=MAD/Median)%>%
  ungroup()

#Export
write.csv(Network_Median_MADs,file = "~",row.names=F)

```

#Calculate CVs for Action Potential Propagation
```{r}
#Indicate input directory
project.input.dir <-"~"


#Make list of data files 
csv_files<- list.files(path=project.input.dir, pattern = "_Melt\\.csv$", recursive = T, full.names = T) 

#Make vector for what the names of the basenames of the data files
data_frame_names<-gsub("_Melt.csv","",basename(csv_files))

#load csv files
for (i in csv_files){
  df<-fread(i)
  df<-df[,-1]
  Axon_Tracking<-df
}

#Check for NAs and remove
Axon_Tracking<-Axon_Tracking%>% filter(!is.na(value))

#Remove DOP 29 (Washout Days)
Axon_Tracking<-subset(Axon_Tracking %>% filter(!grepl(29,DOP)))

Axon_Tracking<-Axon_Tracking%>%filter(!grepl("summary",Endpoint))

#Determine plate type here. Plate serial numbers starting in T are 24-well plate and serial numbers starting in M are 6-well plates
Axon_Tracking<-Axon_Tracking%>%
  mutate(Plate_Type=ifelse(grepl("T",Group_ID),"Twenty_four","Six"))

#Subset control values only 
Axon_Controls<-Axon_Tracking %>% filter((Dosage== "Control"))

#Check for NAs and remove
Axon_Controls<-Axon_Controls%>% filter(!is.na(value))

#set variables as numeric
Axon_Controls$value<-as.numeric(Axon_Controls$value)

#calculate a baseline value by taking the median by endpoint, plate_type and DOP
Axon_Controls[,bval:=median(value),by=c("Endpoint","DOP","Plate_Type")]

#Check for NAs and remove
Axon_Controls <- Axon_Controls[!is.na(bval),]

#Calculate response values by normalizing to bval
Axon_Controls <- Axon_Controls[,resp := ((value) / bval)]

#Group by sample and endpoint
Axon_auc_df<-Axon_Controls %>%
  arrange(DOP)%>%
  group_by(Group_ID,Endpoint) %>%
  summarize (AUC=trapz(DOP,resp))%>%
  ungroup()

#Calculate Median by Endpoint
Axon_Medians<-Axon_auc_df %>%
  group_by(Endpoint) %>%
  summarize (Median=median(AUC))%>%
  ungroup()

#Calculate MAD by Endpoint
Axon_MADs<-Axon_auc_df %>%
  group_by(Endpoint) %>%
  summarize (MAD=mad(AUC))%>%
  ungroup()

#Full join back to one df
Axon_Median_MADs <- full_join(Axon_Medians,MADs, by = c("Endpoint"))

#Calculate CVs based on median and MAD
Axon_CV_Median_Mad<-Axon_Median_MADs%>%
  group_by(Endpoint) %>%
  summarize (CV_Median_MAD=MAD/Median)%>%
  ungroup()

#Export
write.csv(Axon_CV_Median_Mad,file = "~",row.names=F)

```
