---
title: "Longitudinal Analysis (BrainSpheres Week2-10 for General Activity"
author: Sierra Boyd
output:
  html_document:
    theme: cerulean
    toc: false
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

# Load tidyverse and knitr packages

```{r load packages}

library(tidyverse)
library(knitr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggpubr)
library(data.table)
library(conflicted)
library(readxl)
library(openxlsx)
library(patchwork)
conflicts_prefer(purrr::transpose())
conflicts_prefer(dplyr::filter())

```

```{r}
#Set wd to an an "export" folder
setwd("~")

```

#Import files and arrange data
```{r}
#Indicate input directory
project.input.dir <-"~"

#Make list of data files 
csv_files<- list.files(path=project.input.dir, pattern = "_activity\\.csv$", recursive = T, full.names = T) 

#Make vector for what the names of the basenames of the data files
data_frame_names<-gsub("_activity.csv","",basename(csv_files))
data_frame_names<-gsub(" ","_",basename(data_frame_names))
data_frame_names<-gsub("-","_",basename(data_frame_names))
data_frame_names<-gsub("&","_",basename(data_frame_names))
data_frame_names<-gsub("20","k",basename(data_frame_names))

#Function to read in data files and make Group_IDs by separating assayTag
read_datafiles<-function(file){
  file<-read.csv(file)
  file<-file[-c(1),]
  names(file)[1]<-"Instance"
  file$Well.Group.Name<-as.character(file$Well.Group.Name)
  file$Well.Group.Name<-gsub(" ","_",file$Well.Group.Name)
  colnames(file)[which(names(file)=="Well.Group.Name")]<-"Well_Group_Name"
  file$assayTag<-sub("DIV","DOP",file$assayTag)
  file$assayTag<-sub("All Wells", "AllWells",file$assayTag)
  file$assayTag<-gsub("", "",file$assayTag)
  file$assayTag<-gsub("/","w",file$assayTag)
  file$assayTag<-gsub("[(]","{",file$assayTag)
  file$assayTag<-gsub("[)]","}",file$assayTag)
  file$assayTag<-gsub(" ",",",file$assayTag)
  file<- file %>% separate(assayTag, c('DOP','PlateWeek'))
  file$PlateWeek<-gsub("W","",file$PlateWeek)
  file$DOP<-gsub("DOP","",file$DOP)
  file$DOP<-as.numeric(file$DOP)
  file$activeArea<-as.numeric(file$activeArea)
  file$firingRate_mean<-as.numeric(file$firingRate_mean)
  file$amplitude_mean<-as.numeric(file$amplitude_mean)
  file$ISI_mean<-as.numeric(file$ISI_mean)
    file<-as.data.frame(file)
    }
  
#Use the read_datafiles function made above to read in data files
datalist<-lapply(csv_files,read_datafiles)

#Assign the names from the vector data_frame_names to the data frames just read in
for (i in seq_along(datalist)){
  assign(data_frame_names[i],datalist[[i]])
}

#Retrive the actual data frames
data_frames<-mget(data_frame_names)

#Some data files have extra NA columns-remove here 
k231104_W3.4_D5_D33_M04707<-k231104_W3.4_D5_D33_M04707%>%
  select(-c("Media.Type","Cell.Type","Plating.Date"))

k231104_W8.10_D4_D28_M05357<-k231104_W8.10_D4_D28_M05357%>%
  select(-c("Media.Type","Cell.Type","Plating.Date"))

k231104_W8.10_D4_D7_Dk_D28_M04707<-k231104_W8.10_D4_D7_Dk_D28_M04707%>%
  select(-c("Media.Type","Cell.Type","Plating.Date"))

#Retrive the actual data frames
data_frames<-mget(data_frame_names)

RawData<-do.call(rbind,data_frames)

rownames(RawData)<-NULL


```

```{r}

#Per Data Collector Notes- Wells 1-3 are BrainSpheres plated at the earlier time point and Wells 4-6 are BrainSpheres plated at the last time based on the assayTags
RawData<-RawData %>% mutate(PlateWeek= ifelse(wellNo=="1" & PlateWeek=="3w4","Week 3", PlateWeek))
RawData<-RawData %>% mutate(PlateWeek= ifelse(wellNo=="2" & PlateWeek=="3w4","Week 3", PlateWeek))
RawData<-RawData %>% mutate(PlateWeek= ifelse(wellNo=="3" & PlateWeek=="3w4","Week 3", PlateWeek))


RawData<-RawData %>% mutate(PlateWeek= ifelse(wellNo=="4" & PlateWeek=="3w4","Week 4", PlateWeek))
RawData<-RawData %>% mutate(PlateWeek= ifelse(wellNo=="5" & PlateWeek=="3w4","Week 4", PlateWeek))
RawData<-RawData %>% mutate(PlateWeek= ifelse(wellNo=="6" & PlateWeek=="3w4","Week 4", PlateWeek))

RawData<-RawData %>% mutate(PlateWeek= ifelse(wellNo=="1" & PlateWeek=="8w10","Week 8", PlateWeek))
RawData<-RawData %>% mutate(PlateWeek= ifelse(wellNo=="2" & PlateWeek=="8w10","Week 8", PlateWeek))
RawData<-RawData %>% mutate(PlateWeek= ifelse(wellNo=="3" & PlateWeek=="8w10","Week 8", PlateWeek))


RawData<-RawData %>% mutate(PlateWeek= ifelse(wellNo=="4" & PlateWeek=="8w10","Week 10", PlateWeek))
RawData<-RawData %>% mutate(PlateWeek= ifelse(wellNo=="5" & PlateWeek=="8w10","Week 10", PlateWeek))
RawData<-RawData %>% mutate(PlateWeek= ifelse(wellNo=="6" & PlateWeek=="8w10","Week 10", PlateWeek))

RawData<-RawData %>% mutate(PlateWeek= ifelse(wellNo=="1" & PlateWeek=="5w6","Week 5", PlateWeek))
RawData<-RawData %>% mutate(PlateWeek= ifelse(wellNo=="2" & PlateWeek=="5w6","Week 5", PlateWeek))
RawData<-RawData %>% mutate(PlateWeek= ifelse(wellNo=="3" & PlateWeek=="5w6","Week 5", PlateWeek))


RawData<-RawData %>% mutate(PlateWeek= ifelse(wellNo=="4" & PlateWeek=="5w6","Week 6", PlateWeek))
RawData<-RawData %>% mutate(PlateWeek= ifelse(wellNo=="5" & PlateWeek=="5w6","Week 6", PlateWeek))
RawData<-RawData %>% mutate(PlateWeek= ifelse(wellNo=="6" & PlateWeek=="5w6","Week 6", PlateWeek))

RawData<-RawData %>% mutate(PlateWeek= ifelse(wellNo=="1" & PlateWeek=="6w7","Week 6", PlateWeek))
RawData<-RawData %>% mutate(PlateWeek= ifelse(wellNo=="2" & PlateWeek=="6w7","Week 6", PlateWeek))
RawData<-RawData %>% mutate(PlateWeek= ifelse(wellNo=="3" & PlateWeek=="6w7","Week 6", PlateWeek))


RawData<-RawData %>% mutate(PlateWeek= ifelse(wellNo=="4" & PlateWeek=="6w7","Week 7", PlateWeek))
RawData<-RawData %>% mutate(PlateWeek= ifelse(wellNo=="5" & PlateWeek=="6w7","Week 7",  PlateWeek))
RawData<-RawData %>% mutate(PlateWeek= ifelse(wellNo=="6" & PlateWeek=="6w7","Week 7", PlateWeek))

#subset weeks 3w5w7- this was a 24 well plate-Remove since others are 6 well
RawData<-subset(RawData %>% filter(!grepl("3w5w7",PlateWeek)))
```

```{r }
#set DOP and weeks as factros to make sure it plots numerically
order<-c("4", "5","6","7","8", "10", "11", "12","13", "15","16","18", "19","20", "21","22","25","26","27","28","30","33")
RawData$DOP<-factor(RawData$DOP,levels=order)

Weekorder<-c("Week 3","Week 4","Week 5", "Week 6", "Week 7", "Week 8","Week 10")
RawData$PlateWeek<-factor(RawData$PlateWeek,levels=Weekorder)

```

```{r}

#Select needed columns
RawData<-RawData%>%
  select(c("activeArea","firingRate_mean","amplitude_mean","ISI_mean","wellplateID","wellNo","DOP","PlateWeek"))

RawData<-as.data.table(RawData)

#Make the data a long data format
RawData_melt <- melt(RawData, id.vars = c("wellplateID","wellNo","DOP","PlateWeek"),
                          measure.vars =c("activeArea","firingRate_mean","amplitude_mean","ISI_mean"))

#Update variable names
setnames(RawData_melt, "variable","Endpoint")


#Edit Endpoint Names
RawData_melt$Endpoint<-gsub("activeArea","Active Area",RawData_melt$Endpoint)
RawData_melt$Endpoint<-gsub("firingRate_mean","Firing Rate (Hz)",RawData_melt$Endpoint)
RawData_melt$Endpoint<-gsub("amplitude_mean","Spike Amplitude (µV)",RawData_melt$Endpoint)
RawData_melt$Endpoint<-gsub("ISI_mean","Inter-Spike-Interval (ms)",RawData_melt$Endpoint)


#Make vector of the unique endpoints in this df to call below
Endpoint<-unique(RawData_melt$Endpoint)

#Make empty list for plots to fill below
ActivityScan_Control_BoxPlots_plotlist<-list()

#ForLoop to plot all Endpoints
for (j in Endpoint){
   df_subset<-RawData_melt[RawData_melt$Endpoint==j,]
   
   y_min<-min(df_subset$value)
   y_max<-max(df_subset$value)
  
  ActivityScan_Control_BoxPlots<-ggplot(df_subset,aes(x=factor(DOP),y=value))+
  theme_minimal()+
  labs(y="",x="Days on Plate")+
  geom_boxplot(alpha=0.6,position = position_dodge(width=0.7))+
  geom_point(position = position_dodge(width=0.7))+
  theme(legend.position="none")+
  ggtitle(paste(j))+
    scale_y_continuous(limits=c(y_min,y_max))+
    facet_wrap(~PlateWeek,scales='free_x',ncol=1)+
    theme(plot.title = element_text(hjust = 0.5))

    
   print(ActivityScan_Control_BoxPlots)
  
   ActivityScan_Control_BoxPlots_plotlist[[j]]<-ActivityScan_Control_BoxPlots
}

#Put all plots in one figure and save
ActivityScan_Control_BoxPlots<-ggarrange(plotlist=ActivityScan_Control_BoxPlots_plotlist,ncol=4)
ActivityScan_Control_BoxPlots<-annotate_figure(ActivityScan_Control_BoxPlots, top = text_grob("General Activity Ontogeny for Controls",size=14))
ActivityScan_Control_BoxPlots

ggsave("ActivityScanScan_Timeline_BoxPlots.png",plot=ActivityScan_Control_BoxPlots,bg="white",width=12,height=14)
```



